/**
 * SATIM API request payload for payment registration
 * Matches SATIM register.do endpoint
 */
export interface SatimRegisterPaymentRequest {
  userName: string; // Merchant's login
  password: string; // Merchant's password
  orderNumber: string; // Unique order identifier (max 10 chars)
  amount: number; // Amount in centimes, must be multiple of 100, minimum 5000 (50 DA)
  currency: string; // ISO 4217 code (012 for DZD)
  returnUrl: string; // Success redirect URL
  failUrl?: string; // Failure redirect URL
  description?: string; // Order description
  language: string; // ISO 639-1 lowercase: 'fr', 'ar', 'en' (not 'FR', 'AR', 'EN')
  jsonParams: string; // JSON string with force_terminal_id and optional params
}

/**
 * JSON parameters for SATIM register.do
 */
export interface SatimJsonParams {
  force_terminal_id: string; // Terminal ID (mandatory)
  udf1?: string; // User defined field 1
  udf2?: string; // User defined field 2
  udf3?: string; // User defined field 3
  udf4?: string; // User defined field 4
  udf5?: string; // User defined field 5
  fundingTypeIndicator?: string; // Transaction type (e.g., "CP" or "698" for bill payment)
}

/**
 * SATIM API response for payment registration
 */
export interface SatimRegisterPaymentResponse {
  errorCode: string; // "0" for success, other codes for errors
  orderId?: string; // Unique order ID (mdOrder) generated by EPG
  formUrl?: string; // Payment page URL for customer redirect
  errorMessage?: string; // Error description
}

/**
 * SATIM API request for payment verification (acknowledgeTransaction.do)
 */
export interface SatimVerifyPaymentRequest {
  userName: string;
  password: string;
  mdOrder: string; // Order ID returned from registration
  language: string;
}

/**
 * SATIM API response for payment verification (acknowledgeTransaction.do)
 */
export interface SatimVerifyPaymentResponse {
  ErrorCode: string; // "0" for success
  ErrorMessage?: string; // Error description
  OrderStatus?: number; // Order status code (0-11)
  OrderNumber?: string; // Original merchant order number
  Amount?: number; // Order amount in centimes
  currency?: string; // ISO 4217 currency code
  depositAmount?: number; // Amount debited
  expiration?: string; // Card expiry (YYYYMM)
  cardholderName?: string; // Cardholder name
  Pan?: string; // Masked card number (6280****7215)
  authorizationResponseId?: string; // Authorization code (6 chars)
  approvalCode?: string; // IPS authorization code
  actionCode?: number; // Processing system authorization code
  actionCodeDescription?: string; // Action code description
  Ip?: string; // Customer IP address
  clientId?: string; // Customer identifier
  bindingId?: string; // Binding identifier
  paymentAccountReference?: string; // Payment account data
  Description?: string; // Order description
  params?: Record<string, any>; // Additional parameters
  SvfeResponse?: string; // SVFE response code
}

/**
 * SATIM API request for refund (refund.do)
 * According to SATIM documentation: amount must be in same format as register.do
 * For 50 DA order -> amount=5000 (not 500000)
 */
export interface SatimRefundRequest {
  userName: string;
  password: string;
  orderId: string; // mdOrder from registration
  amount: number; // Amount in centimes, same format as register.do (min 100, multiple of 100)
}

/**
 * SATIM API response for refund (refund.do)
 */
export interface SatimRefundResponse {
  errorCode: string; // "0" for success
  errorMessage?: string; // Error description or success message
}

/**
 * Generic SATIM error response
 */
export interface SatimErrorResponse {
  success: false;
  errorCode: string;
  message: string;
  details?: any;
}
